#define GLIB_DISABLE_DEPRECATION_WARNINGS
#include <sys/types.h>
#include <unistd.h>
#include <termios.h>
#include <gdk/gdk.h>
#include <gsk/gsk.h>
#include <gtk/gtkimmodule.h>
#include <gtk/gtk.h>
#include <gtk/gtkunixprint.h>
#include <gtksourceview/gtksource.h>
